image: python:3.11

stages:
  - build
  - test

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python main.py
  only:
    - master

test:
  stage: test
  script:
    - pytest -v
  only:
    - master