image: python:3.11

stages:
  - build
  - test

before_script:
  - python -m venv venv
  - venv\Scripts\activate
  - venv\Scripts\python.exe -m pip install --upgrade pip setuptools
  - venv\Scripts\python.exe -m pip install -r requirements.txt

build:
  stage: build
  script:
    - venv\Scripts\python.exe main.py
  only:
    - master

test:
  stage: test
  script:
    - venv\Scripts\python.exe -m pytest -v
  only:
    - master